# [Start Cloudbuild]
steps:
- id: 'Show branch name'
  name: alpine
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        echo "########################"
        echo "$BRANCH_NAME"
        echo "#########################"