# [Start Cloudbuild]
steps:
- id: 'Show branch name'
  name: alpine
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        echo "########################"
        echo "$BRANCH_NAME"
        echo "#########################"

- id: 'Executing terraform init'
  name: hashicorp/terraform:1.2.3
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        cd ./infra
        terraform init

- id: 'Executing terraform plan'
  name: hashicorp/terraform:1.2.3
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        terraform plan
        