# [Start Cloudbuild]
# [Start Terraform steps init, plan, apply]
steps:
- id: 'Show branch name'
  name: alpine
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        echo "########################"
        echo "$BRANCH_NAME"
        echo "#########################"

- id: 'Executing terraform init'
  name: hashicorp/terraform:1.2.3
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        cd ./infra
        terraform init

- id: 'Executing_terraform_plan'
  name: hashicorp/terraform:1.2.3
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        cd ./infra
        terraform plan -out=tfplan

- id: 'Executing_terraform_apply'
  name: hashicorp/terraform:1.2.3
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        cd ./infra
        terraform apply tfplan
  timeout: 2400s

#[End Terraform steps]
#[Start building the Docker image]
# This step builds the container image.
- id: 'Build the container image'
  name: 'gcr.io/cloud-builders/docker'
  waitFor: ['Executing_terraform_apply']
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/timeoff:$SHORT_SHA'
  - '.'

- id: 'ls image'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'image'
  - 'ls'

#[End building the image]
#[Taging and pushing the image]
substitutions:
  _REPO_NAME: gcp-repo